version: '3.1'

services:
  boxing-fever-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boxingfever
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    environment:
      FLYWAY_URL: jdbc:mysql://localhost:3306/boxingfever
      FLYWAY_USER: user
      FLYWAY_PASSWORD: password
    volumes:
      - ./docker/flyway-conf:/flyway/conf
      - ./docker/migration:/flyway/sql
    command: [ "-url=jdbc:mysql://localhost:3306/boxingfever", "-user=user", "-password=password", "-connectRetries=60",  "migrate" ]
    depends_on:
      - boxing-fever-db

