version: '3.1'

services:
  boxing-fever-db:
    image: mysql:latest
    container_name: boxing-fever-db
    environment:
      MYSQL_DATABASE: boxing-fever
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - boxing-fever-network

networks:
  boxing-fever-network:
    driver: bridge
