version: '3.1'

services:
  boxing-fever-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boxingfever
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

