version: '3.1'

services:
  boxing-fever-db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: boxing-fever
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf