version: '3.1'

services:
  boxing-fever-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: jaCZYzRpPU
      MYSQL_DATABASE: sql11667105
      MYSQL_USER: sql11667105
      MYSQL_PASSWORD: jaCZYzRpPU
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  app:
    image: boxing-fever
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - boxing-fever-db